" alchermd's vimrc configuration
"
" As suggested by the community, this configuration file
" is homegrown from my own needs throughout my vim journey.
"
" Sample usage:
"  $ git clone git@github.com:alchermd/dotfiles.git ~/src/dotfiles
"  $ ln -sf ~/src/dotfiles/.vim ~/.vim

" 3rd-party plugins
call plug#begin()
  Plug 'preservim/nerdtree'
  Plug 'ryanoasis/vim-devicons'
call plug#end()

" NERDTree options
let NERDTreeShowHidden=1
let g:NERDTreeWinPos="right"
autocmd VimEnter * NERDTree

" Filetype-specific indenting, syntax highlighting, omni-completion.
filetype plugin indent on
syntax on
set omnifunc=syntaxcomplete#Complete

" Double tap 'j' to enter normal mode form insert mode
imap jj <Esc> 

" Basic settings
set autoindent
set ruler number " Show line numbers
set encoding=utf-8

" ideavim shortcuts
nnoremap <leader>re :action Refactorings.QuickListPopupAction<CR>
set idearefactormode=keep
